
//ARTIST DATABASE


var andy = {
	"name" : "Andy Grammer",

	"similarArtists" :[
					"Jon McLaughlin",
					"Gavin DeGraw",
					"Jason Reeves",
					"Jason Mraz",
					"The Script"
				]
}

var beatles = {
	"name" : "The Beatles",

	"similarArtists" :[
					"Paul McCartney",
					"The Who",
					"The Zombies",
					"The Velvet Underground",
					"Elton John"
				]
}

var calvin = {
	"name" : "Calvin Harris",

	"similarArtists" :[
					"Avicii",
					"David Guetta",
					"Alesso",
					"Afrojack",
					"Hardwell"
				]
}

var cox = {
	"name" : "Carl Cox",

	"similarArtists" :[
					"Nicole Moudaber",
					"Deep Dish",
					"Umek",
					"Dubfire",
					"Green Velvet"
				]
}

var dangelo = {
	"name" : "D'Angelo And The Vanguard",

	"similarArtists" :[
					"Erykah Badu",
					"Maxwell",
					"D'Angelo",
					"Jill Scott",
					"Lauryn Hill"
				]
}

var digable = {
	"name" : "Digable Planets",

	"similarArtists" :[
					"The Pharcyde",
					"A Tribe Called Quest",
					"Pete Rock",
					"Shabazz Palaces",
					"De La Soul"
				]
}

var drake = {
	"name" : "Drake",

	"similarArtists" :[
					"J. Cole",
					"Big Sean",
					"Wale",
					"Kanye West",
					"Kid Cudi"
				]
}

var fiona = {
	"name" : "Fiona Apple",

	"similarArtists" :[
					"Regina Spektor",
					"Tori Amos",
					"Alanis Morissette",
					"Rachael Yamagata",
					"Jill Sobule"
				]
}

var florence = {
	"name" : "Florence + The Machine",

	"similarArtists" :[
					"Kate Nash",
					"Ellie Goulding",
					"Marina and the Diamonds",
					"Lykke Li",
					"Sia"
				]
}

var flume = {
	"name" : "Flume",

	"similarArtists" :[
					"Chet Faker",
					"Hermitude",
					"What So Not",
					"Bondax",
					"Xxyyxx"
				]
}

var fugazi = {
	"name" : "Fugazi",

	"similarArtists" :[
					"Drive Like Jehu",
					"The Evens",
					"The Dismemberment Plan",
					"Rites of Spring",
					"Jawbox"
				]
}

var ghostland = {
	"name" : "Ghostland Observatory",

	"similarArtists" :[
					"Datarock",
					"Shy Child",
					"Shitdisco",
					"New Young Pony Club",
					"Cut Copy"
				]
}

var iceage = {
	"name" : "Iceage",

	"similarArtists" :[
					"Eagulls",
					"Marching Church",
					"Lust for Youth",
					"Ought",
					"Parquet Courts"
				]
}

var idina = {
	"name" : "Idina Menzel",

	"similarArtists" :[
					"Kristin Chenoweth",
					"Lea Michele",
					"Jason Robert Brown",
					"Joel Grey",
					"Linda Eder"
				]
}

var johnMayer = {
	"name" : "John Mayer",

	"similarArtists" :[
					"Jason Mraz",
					"Jack Johnson",
					"James Morrison",
					"John Mayer Trio",
					"Gavin DeGraw"
				]
}

var kaskade = {
	"name" : "Kaskade",

	"similarArtists" :[
					"deadmau5",
					"Tiesto",
					"Wolfgang Gartner",
					"Late Night Alumni",
					"Morgan Page"
				]
}

var kendrick = {
	"name" : "Kendrick Lamar",

	"similarArtists" :[
					"Kanye West",
					"Schoolboy Q",
					"ASAP Rocky",
					"Ab-Soul",
					"Run The Jewels"
				]
}

var lana = {
	"name" : "Lana del Rey",

	"similarArtists" :[
					"Ellie Goulding",
					"Lykke Li",
					"Lorde",
					"Sky Ferreira",
					"Charli XCX"
				]
}

var mumford = {
	"name" : "Mumford & Sons",

	"similarArtists" :[
					"Noah and the Whale",
					"Edward Sharpe & the Magnetic Zeros",
					"Bombay Bicycle Club",
					"The Tallest Man On Earth",
					"Bon Iver"
				]
}

var oneD = {
	"name" : "One Direction",

	"similarArtists" :[
					"Jonas Brothers",
					"Cher Lloyd",
					"The Wanted",
					"Big Time Rush",
					"McFly"
				]
}

var porter = {
	"name" : "Porter Robinson",

	"similarArtists" :[
					"Mat Zo",
					"Zedd",
					"Dillon Francis",
					"Feed Me",
					"The M Machine"
				]
}

var savages = {
	"name" : "Savages",

	"similarArtists" :[
					"Eagulls",
					"Iceage",
					"The Shadows of Knight",
					"Viet Cong",
					"The Horrors"
				]
}

var shawn = {
	"name" : "Shawn Mendes",

	"similarArtists" :[
					"Magic!",
					"Carly Rae Jepsen",
					"Ed Sheeran",
					"Cody Simpson",
					"Olly Murs"
				]
}

var sleater = {
	"name" : "Sleater-Kinney",

	"similarArtists" :[
					"Bikini Kill",
					"Bratmobile",
					"Heavens to Betsy",
					"Excuse 17",
					"Wild Flag"
				]
}

var tame = {
	"name" : "Tame Impala",

	"similarArtists" :[
					"Unknown Mortal Orchestra",
					"Kurt Vile",
					"Dungen",
					"Deerhunter",
					"Bear in Heaven"
				]
}

var tswift = {
	"name" : "Taylor Swift",

	"similarArtists" :[
					"Carrie Underwood",
					"Miranda Lambert",
					"Kellie Pickler",
					"Lady Antebellum",
					"LeAnn Rimes"
				]
}

var tim = {
	"name" : "Tim McGraw",

	"similarArtists" :[
					"Blake Shelton",
					"Kenny Chesney",
					"Rodney Atkins",
					"Keith Urban",
					"Brad Paisley"
				]
}

var twin = {
	"name" : "Twin Peaks",

	"similarArtists" :[
					"The Orwells",
					"King Tuff",
					"The Soft Pack",
					"Frankie Cosmos",
					"Fidlar"
				]
}

var wavves = {
	"name" : "Wavves",

	"similarArtists" :[
					"Ty Segall",
					"Bass Drum of Death",
					"Cloud Nothings",
					"Best Coast",
					"Deerhunter"
				]
}


var artists = [andy, beatles, calvin, cox, dangelo, digable, drake, fiona, florence, flume, fugazi,
               ghostland, iceage, idina, johnMayer, kaskade, kendrick, lana, mumford, oneD, porter,
              savages, shawn, sleater, tame, tim, tswift, twin, wavves]



//FESTIVAL DATABASE


var obj = {}

//individual festivals
	obj.acl = {
		"festName" : "Austin City Limits",

	  	"location" : "Austin, TX",

		"lineup" :[
						"Foo Fighters",
						"Drake",
						"The Strokes",
						"Florence + The Machine",
						"The Weeknd",
						"Disclosure",
						"deadmau5",
						"Bassnectar",
						"alt-J",
						"Hozier",
						"Alabama Shakes",
						"Of Monsters and Men",
						"Modest Mouse",
						"Tame Impala",
						"Sturgill Simpson",
						"The Decemberists",
						"ASAP Rocky",
						"Gary Clark Jr.",
						"Chance The Rapper",
						"Ben Howard",
						"Brand New",
						"TV On The Radio",
						"G-Eazy",
						"Walk The Moon",
						"Billy Idol",
						"Twenty One Pilots",
						"Nero",
						"Dwight Yoakam",
						"Father John Misty",
						"Brandon Flowers",
						"Vance Joy",
						"George Ezra",
						"Lord Huron",
						"Flosstradamus",
						"Future",
						"Cherub",
						"Run The Jewels",
						"Glass Animals",
						"Sylvan Esso",
						"Shakey Graves",
						"Leon Bridges",
						"Nate Ruess",
						"Halsey",
						"Echosmith",
						"Royal Blood",
						"Misterwives",
						"Kurt Vile And The Violators",
						"José González",
						"Griz",
						"Daughter",
						"Houndmouth",
						"Børns",
						"Rhiannon Giddens",
						"Boots",
						"Strand Of Oaks",
						"Unknown Mortal Orchestra",
						"Vince Staples",
						"Ryn Weaver",
						"Albert Hammond Jr.",
						"Moon Taxi",
						"Classixx",
						"In The Valley Below",
						"Years & Years",
						"Fidlar",
						"Jidenna",
						"Sheppard",
						"Waxahatchee",
						"Milo Greene",
						"San Fermin",
						"Drew Holcomb And The Neighbors",
						"Meg Myers",
						"The Maccabees",
						"Ruen Brothers",
						"Amason",
						"Wolf Alice",
						"Avers",
						"Asleep At The Wheel",
						"Luis Coronel",
						"William Clark Green",
						"Charlotte Oc",
						"Alina Baraz And Galimatias",
						"Ume",
						"Whiskey Myers",
						"Lion Babe",
						"Holychild",
						"Waters",
						"Marian Hill",
						"Son Little",
						"Con Brio",
						"Kaleo",
						"El Tule",
						"The Hunts",
						"Beat Connection",
						"Talk In Tongues",
						"Leopold And His Fiction",
						"The Nightowls",
						"Sons Of Bill",
						"Mandolin Orange",
						"Spirit Family Reunion",
						"The Suffers",
						"Kehlani",
						"Jessica Hernandez & The Deltas",
						"Kali Uchis",
						"American Aquarium",
						"Rayland Baxter",
						"Tameca Jones",
						"Bee Caves",
						"Knifight",
						"The Wind And The Wave",
						"Alessia Cara",
						"Night Drive",
						"Calliope Musicals",
						"Riders Against The Storm",
						"Gabriel Garzón-Montano",
						"In The Whale",
						"Boom Forest",
						"The Eagle Rock Gospel Singers",
						"Sol Cat",
						"The Last Bandoleros",
						"Adia Victoria",
						"Sounds Del Mar",
						"The London Souls",
						"Koa",
						"Muddy Magnolias",
						"Maggie Koerner",
						"Derobert & The Half-Truths",
						"Lanz Pierce",
						"Steelism",
						"Kansas Bible Company",
						"The Marcus King Band",
						"Hunter Sharpe",
						"Sugar + The Hi-Lows",
						"Mikaela Davis",
						"Tyree Morris & Hearts Of Worship",
						"The Levites",
						"Disciples Of Christ",
						"Blessed",
						"A Tribute To Andrae Crouch",
						"The Barton Hills Choir",
						"Wesley Bray & The Disciples Of Joy",
						"Kings Of Harmony +1",
						"Q Brothers",
						"Residual Kid",
						"Emisunshine",
						"Motown Pete",
						"The Pop Ups",
						"Justin Roberts & The Not Ready For Naptime Players",
						"Tim Kubart With Mother Falcon",
						"Mister G",
						"Big Don",
						"School Of Rock"
					],

	  	"tile" : "",

	  	"url" : "../festivals/acl.html"

	}

	obj.bonnaroo = {
		"festName" : "Bonnaroo Music Festival",

	  	"location" : "Manchester, TN",

		"lineup" :[
						"Billy Joel",
						"Mumford & Sons",
						"deadmau5",
						"Kendrick Lamar",
						"Florence + The Machine",
						"Robert Plant & The Sensational Space Shifters",
						"My Morning Jacket",
						"Bassnectar",
						"Alabama Shakes",
						"Childish Gambino",
						"Flume",
						"Hozier",
						"D'Angelo And The Vanguard",
						"Slayer",
						"Ben Harper & The Innocent Criminals",
						"Belle & Sebastian",
						"Spoon",
						"The War On Drugs",
						"STS9",
						"Ben Folds and yMusic",
						"Throwback Superjam Dance Party",
						"Atmosphere",
						"Chris Hardwick",
						"Atomic Bomb! Who Is William Onyeabor Feat. Jamie Lidell",
						"Charles Lloyd",
						"Luke Jenner",
						"Money Mark",
						"Pat Mahoney, Sinkane & Mike Floss",
						"Tears For Fears",
						"Reggie Watts",
						"Brandi Carlile",
						"Twenty One Pilots",
						"The Bluegrass Situation Superjam Featuring Ed Helms And Special Guests",
						"Jeff Ross",
						"Flying Lotus",
						"Earth, Wind & Fire",
						"Caribou",
						"Ralphie May",
						"Gary Clark Jr.",
						"SBTRKT",
						"Kacey Musgraves",
						"Punch Brothers",
						"Medeski, Scofield, Martin & Wood",
						"Tove Lo",
						"ODESZA",
						"Run The Jewels",
						"Dawes",
						"G-Eazy",
						"Tycho",
						"Nick Thune",
						"Trampled By Turtles",
						"Sturgill Simpson",
						"Moon Taxi",
						"AWOLNATION",
						"Sylvan Esso",
						"Béla Fleck And Abigail Washburn",
						"Natasha Leggero",
						"Guster",
						"Jamie xx",
						"Ron Funches",
						"Against Me!",
						"Soja",
						"Jerry Douglas Presents Earls Of Leicester",
						"Bleachers",
						"Rudimental",
						"Mac DeMarco",
						"The Very Vest",
						"Freddie Gibbs and Madlib",
						"Shakey Graves",
						"Shabazz Palaces",
						"Ian Edwards",
						"Gramatik",
						"Mø",
						"Unknown Mortal Orchestra",
						"Jungle",
						"Benjamin Booker",
						"Ari Shaffir",
						"Houndmouth",
						"The Growlers",
						"Glass Animals",
						"SZA",
						"Kurt Braunohler",
						"Courtney Barnett",
						"Rhiannon Giddens",
						"Royal Blood",
						"Tanya Tagaq",
						"Woods",
						"Hurray For The Riff Raff",
						"Big Jay Oakerson",
						"Iceage",
						"Temples",
						"Between The Buried & Me",
						"Dan Soder",
						"Rustie",
						"Ryn Weaver",
						"Dopapod",
						"Pokey Lafarge",
						"Priory",
						"Jamie Lee",
						"Bahamas",
						"Strand Of Oaks",
						"Phox",
						"Gregory Alan Isakov",
						"So Percussion",
						"Brownout Presents Brown Sabbath",
						"The Districts",
						"Cameron Esposito",
						"Madisen Ward And The Mama Bear",
						"DMA'S",
						"Catfish And The Bottlemen",
						"Jon Cleary & The Absolute Monster Gentlemen",
						"The Lonesome Trio",
						"Pallbearer",
						"Songhoy Blues",
						"Matt McCarthy",
						"DeJ Loaf",
						"Christopher Denny",
						"Hiss Golden Messenger",
						"Mark Normand",
						"King Gizzard And The Lizard Wizard",
						"Jessica Hernandez & The Deltas",
						"Unlocking The Truth",
						"Michelle Wolf",
						"April Richardson",
						"New Breed Brass Band",
						"Rubblebucket",
						"Bear's Den",
						"Raury",
						"Little May",
						"Parlour Tricks",
						"Matoma",
						"Alex Funk",
						"Attom",
						"DJ Ascension",
						"DJ Logic",
						"DJ Prince Hakim",
						"E.Feld",
						"Full Service Party",
						"Jai Wolf",
						"Klü",
						"Motion Potion",
						"Quickie Mart",
						"Red Bull Music Academy Takeover",
						"Robe Rage With Special Guest Band",
						"Snicklefritz",
						"The Unsheathed",
						"Tiki Disco",
						"Birdman With Antonio Sánchez",
						"Corey Feldman & The Angels",
						"American Hotel",
						"A Thousand Horses",
						"All Them Witches",
						"Basecamp",
						"B.C. Camplight",
						"Betty Who",
						"Boy Named Banjo",
						"Broncho",
						"Chrome Pony",
						"Clear Plastic Masks",
						"Dark Waves",
						"De Lux",
						"Elle King",
						"Falls",
						"Fruition",
						"Future Thieves",
						"Future Unlimited",
						"Gabriel Garzón-Montano",
						"Grey Season",
						"Highly Suspect",
						"Homemade Wine",
						"Hudson K",
						"Jason Mcmillan Band",
						"Jesse Terry",
						"Joel Woods",
						"Kaleo",
						"Kandace Springs",
						"Kevin Garrett",
						"Knox Hamilton",
						"Mick Jenkins",
						"Mini Mansions",
						"Mispers",
						"Nothing More",
						"Phoebe Ryan",
						"Radiolucent",
						"Smooth Hound Smith",
						"Sol Cat",
						"Son Little",
						"The Dø",
						"The Wind And The Wave",
						"Tor Miller",
						"Twiddle",
						"Wild Atlantic",
						"X Ambassadors",
						"Ximena Sariñana"
					],

	  	"tile" : "",

	  	"url" : "../festivals/bonnaroo.html"

	}

	obj.bpm = {
		"festName" : "The BPM Festival",

	  	"location" : "Playa del Carmen, Mexico",

		"lineup" :[
						"AC Slater",
						"Adriatique",
						"Âme",
						"Apollonia",
						"Art Department",
						"Behrouz",
						"Ben UFO",
						"Benoit & Sergio",
						"Bill Patrick",
						"Boris",
						"Carl Cox",
						"Carl Craig",
						"Carlo Lio",
						"Chaim",
						"Chus & Ceballos",
						"Claude VonStroke",
						"Dan Ghenacia",
						"Davide Squillace",
						"Dixon",
						"DJ Qu",
						"DJ Sneak",
						"DJ Tennis",
						"Dusky",
						"Dyed Soundorom",
						"Eats Everything",
						"Ellen Allien",
						"Gorgon City",
						"Green Velvet",
						"Guti",
						"Guy Gerber",
						"Hector",
						"Henrik Schwarz",
						"Jackmaster",
						"Jamie Jones",
						"Jimmy Edgar",
						"John Digweed",
						"Jon Rundell",
						"Joris Voorn",
						"Joseph Capriati",
						"Joy Orbison",
						"Justin Martin",
						"Kidnap Kid",
						"Lauren Lane",
						"Lee Burridge",
						"Lee Curtiss",
						"Lee Foss",
						"Leon",
						"Loco Dice",
						"Louie Fresco",
						"Luciano",
						"Mano Le Tough",
						"Marco Carola",
						"Marcus Worgull",
						"Mark Knight",
						"Matt Tolfrey",
						"Matthias Tanzmann",
						"Maya Jane Coles",
						"Miguel Puente",
						"Mind Against",
						"My Favorite Robot",
						"Nathan Barato",
						"Navid Izadi (Live)",
						"Nic Fanciulli",
						"Nicole Moudaber",
						"Nitin",
						"No Regular Play (Live)",
						"Patrick Topping",
						"Pleasurekraft",
						"Richy Ahmed",
						"Robbie Akbal",
						"Robert Dietz",
						"Rony Seikaly",
						"Ryan Crosson",
						"Sasha",
						"Scuba",
						"Seth Troxler",
						"Sharam",
						"Shaun Reeves",
						"Shonky",
						"Skream",
						"Solomun",
						"Soul Clap",
						"Stacey Pullen",
						"Steve Lawler",
						"Stimming",
						"Subb-An",
						"Tale Of Us",
						"Tanner Ross",
						"Technasia",
						"The Junkies",
						"The Martinez Brothers",
						"Thugfucker",
						"Tini",
						"Uner",
						"Vaal",
						"Visionquest",
						"Wolf + Lamb",
					],

	  	"tile" : "",

	  	"url" : "../festivals/bpm.html"

	}

	obj.coachella = {
		"festName" : "Coachella Valley Music and Arts Festival",

	  	"location" : "Indio, CA",

		"lineup" :[
						"Ab-Soul",
						"AC/DC",
						"Action Bronson",
						"Addatap",
						"Alabama Shakes",
						"Alchemy",
						"Alesso",
						"Alf Alpha",
						"Alison Wonderland",
						"Allah-Las",
						"alt-J",
						"Alvin Risk",
						"An-Ten-Nae",
						"Andrea Oliva",
						"Andrew Mcmahon In The Wilderness",
						"Angel Olsen",
						"Angus & Julia Stone",
						"Annie Mac",
						"Antemasque",
						"Astronautica",
						"Axwell ^ Ingrosso",
						"Azealia Banks",
						"B.R.E.E.D.",
						"Bad Religion",
						"Bad Suns",
						"Belle & Sebastian",
						"Ben Klock",
						"Benjamin Booker",
						"Bit Funk",
						"Bixel Boys",
						"Brand New",
						"Brant Bjork & The Low Desert Punk Band",
						"Built To Spill",
						"Caribou",
						"Carl Craig",
						"Cashmere Cat",
						"Cassian",
						"Cedric Gervais",
						"Charles Bradley And His Extroidinaires",
						"Chet Faker",
						"Chicano Batman",
						"Chris Malinchak",
						"Circa Survive",
						"Claude VonStroke",
						"Clean Bandit",
						"Cloud Nothings",
						"Clozee",
						"Coasts",
						"Coyote Kisses",
						"Danny Tenaglia",
						"David Guetta",
						"Dem Ham Boyz",
						"Deorro",
						"Desaparecidos",
						"Dirtwire",
						"Dirty South",
						"DJ Harvey",
						"DJ Snake",
						"DJP",
						"Doc Martin feat. Sublevel Live",
						"Drake",
						"Drive Like Jehu",
						"Droog",
						"Duke Dumont",
						"Eagulls",
						"Edu Imbernon",
						"Erol Alkan",
						"Falcons",
						"Father John Misty",
						"Fitz & The Tantrums",
						"FKA twigs",
						"Florence + The Machine",
						"Flosstradamus",
						"Flying Lotus",
						"Fort Knox Five",
						"Freddy Be",
						"Gabe Real",
						"George Ezra",
						"Gesaffelstein",
						"Glass Animals ",
						"Gorgon City",
						"Gramatik",
						"Guy Gerber",
						"Haerts",
						"Hayden James",
						"Hot Natured",
						"Hozier",
						"Interpol",
						"J.E.S.&S.",
						"Jack White",
						"Jackal",
						"Jai Wolf",
						"Jamestown Revival",
						"Jamie xx",
						"Jason Bentley",
						"Jenny Lewis",
						"Jesse Wright",
						"Jimbo Jenkins",
						"Joe Kay & Jay Prince",
						"John Talabot",
						"Jon Hopkins",
						"Joyce Manor",
						"Jungle",
						"Justin Jay",
						"Kasabian",
						"Kaskade",
						"Kaytranada",
						"Keys N Krates",
						"Kiesza",
						"Kimbra",
						"Kygo",
						"Lane 8",
						"Lauren Lane",
						"Lee Foss",
						"Lights",
						"Lil B",
						"Little Red Spiders",
						"Loco Dice",
						"Los Rakas",
						"LOUDPVCK",
						"Lucent Dossier Experience",
						"Lykke Li",
						"M.A.N.D.Y.",
						"Mac DeMarco",
						"Madeon",
						"Mantastique",
						"Marina and The Diamonds",
						"Marques Wyatt",
						"Martin Solveig",
						"Matthew Koma",
						"Mø",
						"Mihkal",
						"Milky Chance",
						"MK",
						"Mor Elian",
						"Moustache",
						"Nero",
						"New World Punx",
						"Night Terrors Of 1927",
						"Nortec Collective Presents: Bostich + Fussible",
						"ODESZA",
						"Off!",
						"Oliver Heldens",
						"Ooah",
						"Panda Bear",
						"Parquet Courts",
						"Peking Duk",
						"Perfume Genius",
						"Pete Tong",
						"Philip Selway",
						"Phox",
						"Porter Robinson",
						"R3Hab",
						"RAC",
						"Radkey",
						"Raekwon & Ghostface Killah",
						"Ratatat",
						"Reverend Horton Heat",
						"Ride",
						"Royal Blood",
						"Ruen Brothers",
						"Run The Jewels",
						"Russ Liquid",
						"Ryan Adams",
						"Ryan Hemsworth",
						"Ryn Weaver",
						"Saint Motel",
						"SBTRKT",
						"Sebastien Leger",
						"Sloan",
						"Soslo",
						"Squarepusher",
						"St. Lucia",
						"St. Paul And The Broken Bones",
						"St. Vincent",
						"Steely Dan",
						"Stromae",
						"Sturgill Simpson",
						"Superduperbrick",
						"Swans",
						"Sylvan Esso",
						"Tale of Us",
						"Tame Impala",
						"The Cribs",
						"The Gaslamp Killer Experience",
						"The Ghost Of A Saber Tooth Tiger",
						"The Orwells",
						"The War On Drugs",
						"The Weeknd",
						"Tiger And Woods",
						"Till Von Sein",
						"tINI",
						"Todd Terje And The Olsens",
						"Toro y Moi",
						"Touche Amore",
						"Tourist",
						"Trent Cantrelle",
						"Trippy Turtle",
						"Tycho",
						"Tyler The Creator",
						"Until The Ribbon Breaks",
						"Vance Joy",
						"Vic Mensa",
						"What So Not",
						"Yelle",
						"Yellow Claw"
					],

	  	"tile" : "",

	  	"url" : "../festivals/coachella.html"

	}

	obj.dirtybird = {
		"festName" : "Dirtybird Campout",

	  	"location" : "Silverado, CA",

		"lineup" :[
						"Claude VonStroke",
						"Justin Martin",
						"Lee Foss",
						"Daniel Bell",
						"J.Phlip",
						"Route 94",
						"Breach",
						"Benoit & Sergio",
						"Laura Jones",
						"Lunice",
						"Nosaj Thing",
						"Eprom",
						"Kill Frenzy",
						"Justin Jay",
						"Jesse Rose",
						"Doorly",
						"&Me",
						"Solar",
						"Genghis Clan",
						"Ardalan",
						"Sonny Fodera",
						"Christian Martin",
						"Worthy",
						"Mikey Lion",
						"Billy Kenny",
						"ZDS",
						"Will Clarke",
						"Walker & Royce",
						"Sacha Robotti",
						"Mark Starr",
						"Ryan Wells",
						"Barclay Crenshaw"
					],

	  	"video" : "",

	  	"url" : "../festivals/dirtybird.html"

	}

	obj.glastonbury = {
		"festName" : "Glastonbury Festival",

	  	"location" : "Glastonbury, England",

		"lineup" :[
						"Foo Fighters",
						"Kanye West",
						"The Who",
						"Florence + The Machine",
						"Pharrell Williams",
						"Paul Weller",
						"Motörhead",
						"Paloma Faith",
						"alt-J",
						"Mary J. Blige",
						"Lionel Richie",
						"Alabama Shakes",
						"Patti Smith",
						"Burt Bacharach",
						"George Ezra",
						"The Waterboys",
						"Hozier",
						"Courtney Barnett",
						"James Bay",
						"Chronixx",
						"Songhoy Blues",
						"Michael Clark Company",
						"The Unthanks",
						"Burtle Silver Band",
						"Rudimental",
						"deadmau5",
						"The Chemical Brothers",
						"Mark Ronson",
						"Ben Howard",
						"Jamie T",
						"The Courteeners",
						"The Maccabees",
						"Belle & Sebastian",
						"The Vaccines",
						"Clean Bandit",
						"Future Islands",
						"Jungle",
						"Ella Eyre",
						"Twin Atlantic",
						"Catfish And The Bottlemen",
						"Everything Everything",
						"Young Fathers",
						"The Cribs",
						"Palma Violets",
						"Azealia Banks",
						"Adam Cohen",
						"Frank Turner",
						"Soak",
						"Swim Deep",
						"Rival Sons",
						"Hot Chip",
						"The Mothership Returns: George Clinton, Parliament, Funkadelic & The Family Stone",
						"Flying Lotus",
						"Caribou",
						"Todd Terje & The Olsens",
						"FKA twigs",
						"Run The Jewels",
						"Vintage Trouble",
						"Roy Ayers",
						"The Gaslamp Killer Experience",
						"Gregory Porter",
						"Steel Pulse",
						"Kasai Allstars",
						"Soil & Pimp Sessions",
						"Cumbia All Stars",
						"Marcos Valle",
						"Sinkane",
						"Hiatus Kaiyote",
						"Dorian Concept",
						"Jane Weaver",
						"Ibibio Sound Machine",
						"Cambodian Space Project",
						"K.O.G & The Zongo Brigade",
						"Flamingods",
						"Super Furry Animals",
						"Jon Hopkins",
						"Ryan Adams",
						"Jamie xx",
						"Spiritualized",
						"Goat",
						"Mavis Staples",
						"The Fall",
						"Sharon Van Etten",
						"Father John Misty",
						"Perfume Genius",
						"Wolf Alice",
						"Kate Tempest",
						"Fat White Family",
						"Benjamin Booker",
						"Gaz Coombes",
						"The Staves",
						"Glass Animals",
						"Giant Sand",
						"Rae Morris",
						"Pussy Riot",
						"Shlomo",
						"Ibeyi",
						"Jack Garratt",
						"King Gizzard",
						"Eaves",
						"Rhodes",
						"Flo Morrissey",
						"Denai Moore",
						"Enter Shikari",
						"Suede",
						"FFS (Franz Ferdinand & Sparks)",
						"Modestep",
						"La Roux",
						"Deathcab For Cutie",
						"SBTRKT",
						"Death From Above 1979",
						"Lianne Le Havas",
						"Circa Waves",
						"Jessie Ware",
						"Charli XCX",
						"Peace",
						"Years And Years",
						"Django Django",
						"Chet Faker",
						"The Pop Group",
						"Alvays",
						"The Districts",
						"Sleaford Mods",
						"Prides",
						"Leon Bridges",
						"Slaves",
						"Saint Raymond",
						"Rainy Boy Sleep",
						"Coasts",
						"Mini Mansions",
						"Christy Moore",
						"The Moody Blues",
						"The Proclaimers",
						"Nick Lowe, Paul Carrack & Andy",
						"Fairweather Low",
						"Wilko Johnson",
						"Texas",
						"Donovan",
						"Tommy Emmanuel",
						"Jack Savoretti",
						"Eric Bibb",
						"Fatboy Slim",
						"Flight Facilities",
						"Four Tet",
						"Fuse Odg",
						"Gorgon City",
						"Herbert Live",
						"Idris Elba",
						"Jess Glynne",
						"Jesus",
						"Leftfield",
						"Sigma",
						"Skepta",
						"Tourist",
						"Tricky",
						"Alo Wala",
						"Andreye",
						"Batida",
						"Bunji Garlin",
						"Krept & Konan",
						"Hannah Wants",
						"Milky Chance",
						"Rag 'n' Bone Man",
						"Roni Size",
						"Bear'S Den",
						"Cara Dillon",
						"Dreadzone",
						"I Am Kloot",
						"Idlewild",
						"King Creosote",
						"Lamb",
						"Lulu",
						"Molotov Jukebox",
						"Moulettes",
						"Neville Staple Band",
						"Raghu Dixit",
						"Seth Lakeman",
						"The Zombies",
						"La Soirée",
						"Svalbard",
						"Eric McGill",
						"Frisky & Mannish",
						"Los Excentricos",
						"Palo Volador",
						"John Hegley",
						"VIP Puppets",
						"Dr John Cooper Clarke",
						"Lords Of Strut",
						"Les Bubb",
						"The Insect Circus Show",
						"Murray Lachian Young",
						"Professor Elemental",
						"Shappi Khorsandi",
						"Demon Barbers",
						"Public Service Broadcasting",
						"Alabama 3",
						"Slamboree",
						"Nic Fanciulli",
						"Annie Nightingale",
						"Dub Pistols",
						"Paul Woolford",
						"Don Letts",
						"Way Out West",
						"Eat Static",
						"Billy Bragg",
						"Thea Gilmore",
						"Buzzcocks",
						"Sam Duckworth & (The Brackets)",
						"Akala",
						"Professor Stephen Hawking",
						"Coreo",
						"Cheebies Alex & Katie'S Roadshow",
						"Re-Play Music",
						"Panic Circus",
						"Rhubarb Theatre",
						"Dynamo",
						"Milkshake Live",
						"DNA",
						"The Flying Seagull Project",
						"Mr Yipadee",
						"Metamorphosis",
						"Adam Beyer",
						"Groove Armada",
						"Spor",
						"Maceo Plex",
						"Booka Shade",
						"Pan-Pot",
						"Skream",
						"The Bug",
						"Foreign Beggars",
						"Cerrone",
						"Phuture",
						"Joe Claussell",
						"Awesome Tapes From Africa",
						"Jah Shaka",
						"Robert Hood",
						"Mr G",
						"Point G",
						"Honey Dijon",
						"Prosumer",
						"Fast Eddie",
						"Caspa",
						"Mickey Finn",
						"Jackmaster B2B Joy Orbison",
						"Skints",
						"Zion Train",
						"Hospital Records",
						"Norman Jay",
						"Babyhead",
						"Bez",
						"Dillinja",
						"808 State",
						"Primal Scream",
						"Mercadonegro",
						"Ricardo Lemvo",
						"Angel Y La Mecanica Loca"
					],

	  	"video" : "",

	  	"url" : "glastonbury"

	}

	obj.govball = {
		"festName" : "Governors Ball",

	  	"location" : "New York, NY",

		"lineup" :[
						"Drake",
						"Florence + The Machine",
						"My Morning Jacket",
						"Chromeo",
						"St. Vincent",
						"The Decemberists",
						"Ratatat",
						"Death From Above 1979",
						"Charli XCX",
						"ODESZA",
						"Rudimental",
						"Future",
						"Vance Joy",
						"Mø",
						"Gorgon City",
						"Benjamin Booker",
						"Diiv",
						"Rae Sremmurd",
						"People Under the Stars",
						"Priory",
						"Black Pistol Fire",
						"The Districts",
						"Deadmau5",
						"Björk",
						"Ryan Adams",
						"Flume",
						"Conor Oberst",
						"SBTRKT",
						"Little Dragon",
						"Future Islands",
						"Atmosphere",
						"Sharon van Etten",
						"Marina and The Diamonds",
						"Clean Bandit",
						"Angus & Julia Stone",
						"Kiesza",
						"J. Roddy Walson & The Business",
						"Moon Taxi",
						"Rustie",
						"White Lung",
						"Kate Tempest",
						"Astr",
						"Holychild",
						"Charlotte OC",
						"The Black Keys",
						"Lana del Rey",
						"Noel Gallagher's High Flying Birds",
						"Tame Impala",
						"Hot Chip",
						"The War on Drugs",
						"Weird Al Yankovic",
						"Big Gigantic",
						"Flying Lotus",
						"A-trak",
						"Royal Blood",
						"Logic",
						"Sturgill Simpson",
						"Mayer Hawthorne",
						"Echosmith",
						"Strand of Oaks",
						"Chronixx and the Zincfence Redemption",
						"Bishop Nehru",
						"Streets of Laredo",
						"DMA's",
						"Hermitude",
						"The Picturebooks"
					],

	  	"video" : "",

	  	"url" : "../festivals/govBall.html"

	}


	obj.lolla = {
		"festName" : "lollapalooza",

	  	"location" : "",

		"lineup" :[
						"Paul McCartney",
						"Metallica",
						"Florence + The Machine",
						"Sam Smith",
						"Bassnectar",
						"The Weeknd",
						"alt-J",
						"Alabama Shakes",
						"Of Monsters and Men",
						"Kaskade",
						"Kid Cudi",
						"Alesso",
						"Tame Impala",
						"ASAP Rocky",
						"Brand New",
						"TV On The Radio",
						"Nero",
						"Dillon Francis",
						"Kygo",
						"Carnage",
						"Twenty One Pilots",
						"G-Eazy",
						"Gary Clark Jr.",
						"Nicky Romero",
						"Flying Lotus",
						"DJ Snake",
						"Hot Chip",
						"The War On Drugs",
						"Father John Misty",
						"Walk The Moon",
						"Marina and The Diamonds",
						"Tyler, The Creator",
						"FKA twigs",
						"The Tallest Man on Earth",
						"Cold War Kids",
						"Lord Huron",
						"Albert Hammond Jr.",
						"Gogol Bordello",
						"Banks",
						"Sylvan Esso",
						"MS MR",
						"Chet Faker",
						"Sturgill Simpson",
						"ODESZA",
						"Tove Lo",
						"The Chainsmokers",
						"Toro y Moi",
						"Charli XCX",
						"Logic",
						"Boys Noize",
						"St. Paul And The Broken Bones",
						"Death From Above 1979",
						"RL Grime",
						"Glass Animals",
						"Django Django",
						"First Aid Kit",
						"Delta Spirit",
						"DJ Mustard",
						"Wild Belle",
						"Twin Peaks",
						"James Bay",
						"Angus & Julia Stone",
						"Broods",
						"Misterwives",
						"George Ezra",
						"Givers",
						"Strand Of Oaks",
						"Ryn Weaver",
						"Moon Taxi",
						"Travi$ Scott",
						"Shakey Graves",
						"Caked Up",
						"What So Not",
						"Hermitude",
						"SZA",
						"Galantis",
						"Jamestown Revival",
						"Wet",
						"Philip Selway",
						"Holychild",
						"Night Terrors Of 1927",
						"Young Thug",
						"Alison Wonderland",
						"Circa Waves",
						"Coasts",
						"DMA'S",
						"Destructo",
						"Catfish And The Bottlemen",
						"Zella Day",
						"Sheppard",
						"Mako",
						"BØRNS",
						"Skylar Spence",
						"Badbadnotgood",
						"Mt. Eden",
						"The Wombats",
						"Halsey",
						"Mighty Oaks",
						"Jessica Hernandez & The Deltas",
						"Bear's Den",
						"SNBRN",
						"Elle King",
						"Lion Babe",
						"Beat Connection",
						"Mick Jenkins",
						"Peking Duk",
						"Black Pistol Fire",
						"Raury",
						"Jack Novak",
						"Black Tiger Sex Machine",
						"Pell",
						"Vérité",
						"Spookyland",
						"jackLNDN",
						"Zebra Katz",
						"The Lonely Biscuits",
						"White Sea",
						"Bully",
						"Hippo Campus",
						"Coin",
						"Lany",
						"Gabriel Garzón-Montano",
						"Slaptop",
						"sirenXX",
						"In The Whale",
						"Atarah Valentine",
						"Kyle Thornton & The Company",
						"The New Pacific",
						"Daye Jack",
						"Janelle Kroll",
						"Nghtmre",
						"Light Em Up",
						"Big Once And Trentino",
						"The Pop Ups",
						"Danny Weinkauf",
						"Motown Pete",
						"Q Brothers",
						"School Of Rock Allstars",
						"The Jimmies",
						"Mista Cookie Jar & The Chocolate Chips",
						"The Helmets"
					],

	  	"video" : "",

	  	"url" : "../festivals/lolla.html"

	}

	obj.made = {
		"festName" : "Budweiser Made in America",

	 	"location" : "Philadelphia, PA",

		"lineup" :[
						"Beyoncé",
						"The Weeknd",
						"Axwell ^ Ingrosso",
						"J. Cole",
						"Bassnectar",
						"Modest Mouse",
						"Death Cab for Cutie",
						"Banks",
						"Meek Mill",
						"Big Sean",
						"Future",
						"Duke Dumont",
						"A-trak",
						"Santigold",
						"Nick Jonas",
						"Metric",
						"De La Soul",
						"G-Eazy",
						"Dj Mustard",
						"GTA",
						"Cedric Gervais",
						"Claud vonStroke",
						"Fabolous",
						"Halsey",
						"Action Bronson",
						"Earl Sweatshirt",
						"Ryan Hemsworth",
						"Vic Mensa",
						"Burns",
						"Botnek",
						"Aeroplane",
						"Jacob Plant",
						"Saint Motel",
						"Young Rising Sons",
						"Grits & Biscuits",
						"The Struts",
						"Flatbush Zombies",
						"Lola Wolf",
						"Creepoid",
						"Superheaven",
						"Hop Along",
						"Waxahatchee",
						"Strand of Oaks",
						"Remy Banks",
						"Mick Jenkins",
						"Marian Hill",
						"Post Malone",
						"Mayaeni",
						"Bas",
						"Cozz",
						"Omen"
					],

	  	"video" : "",

	  	"url" : "../festivals/madeInAmerica.html"
	}

	obj.outsidelands = {
		"festName" : "Outside Lands",

	 	"location" : "San Francisco, CA",

		"lineup" :[
						"Elton John",
						"Mumford & Sons",
						"The Black Keys",
						"Sam Smith",
						"Kendrick Lamar",
						"Wilco",
						"Axwell ^ Ingrosso",
						"Tame Impala",
						"Amon Tobin: Isam 2.0",
						"D'Angelo And The Vanguard",
						"St. Vincent",
						"Porter Robinson",
						"Ben Harper & The Innocent Criminals",
						"Billy Idol",
						"G-Eazy",
						"Hot Chip",
						"Slightly Stoopid",
						"Caribou",
						"Milky Chance",
						"Chet Faker",
						"The Devil Makes Three",
						"Nate Ruess",
						"ODESZA",
						"Cold War Kids",
						"First Aid Kit",
						"Toro y Moi",
						"RL Grime",
						"Lake Street Dive",
						"Mac DeMarco",
						"George Ezra",
						"Iration",
						"Lindsey Stirling",
						"Angus & Julia Stone",
						"DJ Mustard",
						"St. Paul And The Broken Bones",
						"Glass Animals",
						"Laura Marling",
						"James Bay",
						"Get Real",
						"Django Django",
						"Classixx",
						"Karl Denson'S Tiny Universe",
						"Broods",
						"Sky Ferreira",
						"Leon Bridges",
						"Robert DeLong",
						"Unknown Moral Orchestra",
						"SZA",
						"Allah-Las",
						"Shakey Graves",
						"Dan Deacon",
						"Benjamin Booker",
						"Misterwives",
						"The Drums",
						"Langhorne Slim & The Law",
						"Ryn Weaver",
						"Hurray For The Riff Raff",
						"Giraffage",
						"Givers",
						"Wolf Alice",
						"Twin Peaks",
						"The Family Crest",
						"The Revivalists",
						"Waters",
						"Metz",
						"Strand Of Oaks",
						"Speedy Ortiz",
						"DMA'S",
						"Natalie Prass",
						"Alex Bleeker And The Freaks: Play Dead",
						"The Sam Chase",
						"Devon Baldwin",
						"Heartwatch (Fka The Tropics)",
						"Arann Harris And The Farm Band",
						"B-Stars",
						"Dustbowl Revival",
						"The Easy Leaves Duo",
						"M. Lockwood Porter",
						"Red Meat",
						"Wolf + Lamb",
						"Soul Clap",
						"Jimmy Edgar",
						"Kidnap Kid",
						"Jonas Rathsman",
						"Moon Boots",
						"Light Year",
						"Brother In Arms (J.Boogie And Dj Theory)",
						"Floorwax (Feat. Motion Potion & Dj Zeph)",
						"DJ M3",
						"Davey D",
						"Vitamindevo",
						"DJ Page Hodel",
						"DJ Icon",
						"Justin Milla",
						"Shooey"
					],

	  	"video" : "",

	  	"url" : "../festivals/outsidelands.html"
	}

	obj.pitchfork = {
		"festName" : "Pitchfork",

	 	"location" : "Chicago, IL",

		"lineup" :[
						"Wilco",
						"Sleater-Kinney",
						"Chance the Rapper",
						"Ought",
						"Vic Mensa",
						"Todd Terje & The Olsens",
						"CVRCHES",
						"Sophie",
						"Run The Jewels",
						"Iceage",
						"Future Islands",
						"A.G.Cook",
						"Panda Bear",
						"Shamir",
						"Caribou",
						"Tobias Jesso Jr.",
						"The New Pornographers",
						"Clark",
						"Mac DeMarco",
						"ASAP Ferg",
						"Jamie xx",
						"Steve Gunn",
						"Parquet Courts",
						"How to Dress Well",
						"ILOVEMAKONNEN",
						"Ariel Pink",
						"Courtney Barnett",
						"Jessica Pratt",
						"Kurt Vile and the Violators",
						"Perfume Genius",
						"Natalie Prass",
						"Vince Staples",
						"Freddie Gibbs and Madlib",
						"Ryley Walker",
						"Ex Hex",
						"The Julie Ruin",
						"Mr Twin Sister",
						"Waxahatchee",
						"Future Brown",
						"Mourn",
						"Bully",
						"Viet Cong",
						"Protomartyr",
						"Single Mothers",
						"Jimmy Whispers",
						"Bitchin Bajas"
					],

	  	"video" : "",

	  	"url" : "../festivals/pitchfork.html"
	}

	obj.sasquatch = {
		"festName" : "Sasquatch! Music Festival",

	 	"location" : "",

		"lineup" :[
						"Kendrick Lamar",
						"Robert Plant",
						"Modest Mouse",
						"Lana Del Rey",
						"Ryan Adams",
						"Of Monsters and Men",
						"The Decemberists",
						"Tame Impala",
						"St. Vincent",
						"Flume",
						"Spoon",
						"James Blake",
						"Chromeo",
						"Hot Chip",
						"SBTRKT",
						"Schoolboy Q",
						"The New Pornographers",
						"The War On Drugs",
						"The Glitch Mob",
						"Little Dragon",
						"Gogol Bordello",
						"Father John Misty",
						"Run The Jewels",
						"Jose Gonzalez",
						"Jenny Lewis",
						"Milky Chance",
						"Twenty One Pilots",
						"Mø",
						"Kiesza",
						"Real Estate",
						"Future Islands",
						"ODESZA",
						"Royal Blood",
						"Ab-Soul",
						"Shovels & Rope",
						"Glass Animals",
						"SOHN",
						"Jungle",
						"Sharon Van Etten",
						"Action Bronson",
						"Perfume Genius",
						"Dilated Peoples",
						"Cashmere Cat",
						"Sylvan Esso",
						"Temples",
						"Rustie",
						"Milo Greene",
						"Woods",
						"Shakey Graves",
						"Courtney Barnett",
						"Slow Magic",
						"St. Paul And The Broken Bones",
						"Benjamin Booker",
						"The Budos Band",
						"The Knocks",
						"King Tuff",
						"Sam Lachow",
						"San Mangan + Blacksmith",
						"Fences",
						"Phox",
						"San Fermin",
						"Black Pistol Fire",
						"Alvvays",
						"Fuzz",
						"Strand Of Oaks",
						"Raury",
						"Will Butler",
						"The Districts",
						"Twin Peaks",
						"Ruen Brothers",
						"Kate Tempest",
						"Quilt",
						"Merchandise",
						"Hiss Golden Messenger",
						"Nothing",
						"Bishop Nehru",
						"Ex Hex",
						"Diarrhea Planet",
						"Ought",
						"Lizzo",
						"Natalie Prass",
						"Tala",
						"Rose Windows",
						"Blank Range",
						"Grynch",
						"My Goodness",
						"The Young Evils",
						"The Maldives",
						"Kinski",
						"S (Jenn Ghetto)",
						"Porter Ray",
						"Black Whales",
						"Cataldo",
						"Manatee Commune",
						"Smokey Brights",
						"Thunderpussy",
						"Shaprece",
						"Vox Mod",
						"Djao",
						"Ayron Jones & The Way",
						"Murder Vibes",
						"Comedy: Doug Benson",
						"Leslie Jones",
						"Pete Davidson",
						"Cameron",
						"Esposito",
						"Chris Gethard",
						"Nick Thune",
						"Emmett Montgomery",
						"Yogi Paliwal"
					],

	  	"video" : "",

	  	"url" : "../festivals/sasquatch.html"
	}

	obj.stagecoach = {
		"festName" : "Stagecoach Festival",

	 	"location" : "Indio, CA",

		"lineup" :[
						"Tim McGraw",
						"Jake Owen",
						"Kip Moore",
						"Merle Haggard",
						"Kacey Musgraves",
						"The Devil Makes Three",
						"Parmalee",
						"The Time Jumpers",
						"Vince Gill",
						"Dawn Sears",
						"Kenny Sears",
						"Ranger Doug Green",
						"Sturgill Simpson",
						"The Lone Bellow",
						"Brothers Osborne",
						"Parker Millsap",
						"The Handsome Family",
						"Lydia Loveless",
						"Pegi Young",
						"Lindsay Lou & The Flatbellys",
						"Can Ochs",
						"Miranda Lambert",
						"Dierks Bentley",
						"Justin Moore",
						"ZZ Top",
						"Eli Young Band",
						"Gregg Allman",
						"Cassadee Pope",
						"Cast of Nashville",
						"Charles Esten",
						"Clare Bowen",
						"Chris Carmac",
						"Steve Earle",
						"The Cadillac Three",
						"Mickey Gilley",
						"Mac Davis",
						"Nikki Lane",
						"John Moreland",
						"John & Jacob",
						"The Quere Sisters Band",
						"Daniel Romano",
						"Della Mae",
						"Clare Dunn",
						"Anais Mitchell",
						"Old Salt Union",
						"Blake Shelton",
						"The Band Perry",
						"Sara Evans",
						"George Thorogood and the Destroyers",
						"Jerrod Neimann",
						"Frankie Ballard",
						"The Oak Ridge Boys",
						"Hot Rize",
						"Outlaws",
						"Eric Burdon and the Animals",
						"The Swon Brothers",
						"Maddie & Tae",
						"Chris Janson",
						"Keith Anderson",
						"Chatham County Line",
						"Logan Brill",
						"Luke Amelang",
						"Ben Miller Band",
						"Andrew Combs"
					],

	  	"video" : "",

	  	"url" : "../festivals/stagecoach.html"
	}

	obj.tortuga = {
		"festName" : "Tortuga Music Festival",

	 	"location" : "Fort Lauderdale, FL",

		"lineup" :[
						"Kenny Chesney",
						"Zac Brown Band",
						"Jake Owen",
						"Little Big Town",
						"Trace Adkins",
						"Sublime with Rome",
						"David Nail",
						"The Mavericks",
						"Colt Ford",
						"Chase Rice",
						"Sam Hunt",
						"Frankie Ballard",
						"Chase Bryant",
						"The Dirty Guv'nahs",
						"The Cadillac Three",
						"Old Dominion",
						"Maddie & Tae",
						"Nikki Lane",
						"Brooke Eden",
						"Drake White and The Big Fire",
						"Judah & The Lion"
					],

	  	"video" : "",

	  	"url" : "../festivals/tortuga.html"
	}

	obj.ultra = {
		"festName" : "Ultra Music Festival",

	 	"location" : "Miami, FL",

		"lineup" :[
						"Tiesto",
						"Avicii",
						"Alesso",
						"Afrojack",
						"Dash Berlin",
						"Oliver Heldens",
						"3LAU",
						"AronChupa",
						"Axwell ^ Ingrosso",
						"Hardwell",
						"Armin Van Buuren",
						"Martin Garrix",
						"Steve Aoki",
						"Fedde Le Grand",
						"W&W",
						"Blasterjaxx",
						"Ansolo",
						"Vicetone",
						"Michael Calfan",
						"Kryoman",
						"Skrillex",
						"David Guetta",
						"Steve Angello",
						"Knife Party",
						"Nicky Romero",
						"DJ Snake",
						"Robin Schulz",
						"Cazzette",
						"Matthew Koma",
						"Mykris",
						"Tommie Sunshine",
						"Röyksopp",
						"Chromeo",
						"ODESZA",
						"Todd Terje",
						"RAC",
						"Bakermat",
						"Bassnectar",
						"Die Antwood",
						"Big Gigantic",
						"Kiesza",
						"Clean Bandit",
						"Gorgon City",
						"Klingande",
						"Anamanaguchi",
						"Afrobeta",
						"Litchfield",
						"Kygo",
						"Porter Robinson",
						"Netsky",
						"Krewella",
						"Claptone",
						"ASTR",
						"Breate Carolina",
						"Goldfish",
						"Carl Cox",
						"Marco Carola",
						"Adam Beyer",
						"Ida Engberg",
						"Hot Since 82",
						"Jon Rundell",
						"Loco Dice",
						"John Digweed",
						"Seth Troxler",
						"MK",
						"Eats Everything",
						"Cassy",
						"Yousef",
						"Saeed Younan",
						"Paul van Dyk",
						"Eric Prydz",
						"Andrew Bayer",
						"Markus Schulz",
						"Andrew Rayel",
						"Marlo",
						"Heatbeat",
						"Mark Sixma",
						"Maceo Plex",
						"Tale of Us",
						"Dixon",
						"Sasha",
						"Guy J",
						"Mane Le Tough",
						"Dj Tennis",
						"Totally Enormous Extinct Dinosaurs",
						"Get Real",
						"tINI",
						"Guti",
						"Joseph Capriati",
						"Umek",
						"Marco Bailey",
						"Nic Fanciulli",
						"Joris Voorn",
						"Chus & Ceballos",
						"Agoria",
						"andhim",
						"Jamie Jones",
						"Art Department",
						"The Martinez Brothers",
						"Apollonia",
						"Guy Gerber",
						"Pete Tong",
						"Kölsch",
						"Lauren Lane",
						"Camilo Franco",
						"Adrian Hour",
						"Zeds Dead",
						"GTA",
						"Andy C",
						"Excision",
						"12th Planet",
						"Yellow Claw",
						"Grandtheft",
						"Raiden",
						"Ksuke",
						"Cedric Gervais",
						"Dirty South",
						"Boys Noize",
						"Deep Dish",
						"Laidback Luke",
						"Tchami",
						"Galantis",
						"Tommy Trash",
						"Sunnery James & Ryan Marciano",
						"MAKJ",
						"Cash Cash",
						"Rodrigo Vieira + Paciornik",
						"Bonobo",
						"The Magician",
						"Tensnake",
						"Cashmere Cat",
						"Thomas Jack",
						"Goldroom",
						"Klangkarussell",
						"Le Youth",
						"Jauz",
						"Solidisco",
						"Jessie Andrews",
						"EDX",
						"Vinai",
						"Don Diablo",
						"Syn Cole",
						"Firebeatz",
						"Michael Brun",
						"Henrik B",
						"Marcus Schossow",
						"Ookay",
						"Antiserum",
						"Brillz",
						"Party Favor",
						"Branchez",
						"Crizzly",
						"Bixel Boys",
						"Kennedy Jones",
						"Luminox",
						"TWRK",
						"Matoma",
						"Wiwek",
						"Salva",
						"Jack Beats",
						"AC Slater",
						"Milo & Otis",
						"Valentino Khan",
						"Carmada",
						"Aryay",
						"Alvaro",
						"Moti",
						"Rebecca & Fiona",
						"Adam Trigger",
						"DJ Icey",
						"Baby Anne",
						"Los De La Vega",
						"DJ Nate Campbell",
						"Ranidu",
						"Ørjan Nilsen",
						"Giuseppe Ottaviani",
						"Solarstone",
						"Jochen Miller",
						"Sied Van Riel",
						"Khomha",
						"David Gravell",
						"Dallas K",
						"Ruben De Ronde",
						"Ben Gold",
						"Nifra",
						"Nore En Pure",
						"Sleepy & Boo",
						"Stefano Noferini",
						"Dosem",
						"Riotgear",
						"Elio Riso",
						"Antz",
						"Arkatec",
						"Rod B & Re Dupre",
						"Maxum",
						"Josefin Rosen",
						"Takshak",
						"Dano",
						"Pedro M",
						"Jimmy Page",
						"Proxxy",
						"Lantern",
						"Dj 2Rip",
						"Teezy",
						"Joe C",
						"Justin Oh",
						"Ale Mora",
						"Tommy Walker",
						"Bass Control",
						"K9",
						"Nova Duet",
						"Dabura",
						"Soul Goodman",
						"Ideal & Jbreak",
						"Richard Fraioli",
						"Redline",
						"Henao",
						"Adrian Hardy",
						"Gromo",
						"Mz Poppinz",
						"Casey Kiss",
						"Unkl' Funkl'",
						"Metaphysical",
						"Blank Range",
						"Wyzzard",
						"Jason Daniel",
						"Jose Esco"				],

	  	"tile" : "",

	  	"url" : "../festivals/ultra.html"
	}


var festivals = [ obj.acl, obj.bonnaroo, obj.bpm, obj.coachella, obj.dirtybird, obj.glastonbury, 
			obj.govball, obj.lolla, obj.made, obj.outsidelands, obj.sasquatch, obj.stagecoach, 
			obj.tortuga, obj.ultra ]


